Сделаны разметки у главной страницы и страницы каталога
htmlacademy-htmlcss/2186809-sedona-35 pull request #2
Opened 2022-10-03 15:17 UTC by AnnaKhVl

Первая набросок разметки у главной страницы index.html и страницы каталога catalog.html

2022-10-27 07:16 UTC, pavel-nyukalo requested changes

2022-10-27 07:16 UTC, pavel-niukalo commented on images/icons/rating-stars-2.svg
> +<svg width="140" height="37" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path d="m9 10 2.1 6.5H18l-5.6 4 2.2 6.5L9 23l-5.6 4 2.2-6.5-5.6-4h6.9L9 10Z" fill="#83B3D3"/></g><g
Здесь лучше экспортировать одну звездочку и потом либо фоном вставить и продублировать (`background-repeat`), либо в разметку будем вставлять необходимое кол-во звезд.

Если понадобится добавить/убавить звезд проще будет `html/css` поправить, чем новую картинку экспортировать

2022-10-27 07:16 UTC, pavel-niukalo commented on images/icons/rating-stars-4.svg
> +<svg width="140" height="37" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path d="m9 10 2.1 6.5H18l-5.6 4 2.2 6.5L9 23l-5.6 4 2.2-6.5-5.6-4h6.9L9 10Z" fill="#83B3D3"/></g><g
А остальные картинки со звездами удалить соответственно

2022-10-27 07:16 UTC, pavel-niukalo commented on images/icons/search-view-table.svg
> +<svg width="48" height="48" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)" fill="#000"><path d="M20 17h-4v6h4v-6ZM32 17h-4v6h4v-6ZM26 17h-4v6h4v-6ZM20 25h-4v6h4v-6ZM32 25h-4v6h
Сейчас у нас картинка экспортирована с обводкой

![image](https://user-images.githubusercontent.com/52506235/198205254-8dcd4070-362e-411e-a212-5023f412d096.png)

Но если глянуть на стайлгайд, то обводка должна меняться при фокусе например

![image](https://user-images.githubusercontent.com/52506235/198211423-6e1533bc-1cba-49b2-b452-2a5626cfaf5e.png)

Эту обводку будем делать через `css`, поэтому лучше экспортировать маленькие картинки снизу

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +          <img class="page-header-logo" src="images\head-logo-sedona.svg" width="140" height="70" alt="Логотип «Город Седона».">
Слешы надо сделать в обратную сторону, это надежнее и плюс валидатор ругается на такие 

![image](https://user-images.githubusercontent.com/52506235/198212299-09fc4f77-acbb-4f0b-9701-d50f3f28ab87.png)

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +              <img class="icon-search" src="images\icons\navigation-loop.svg" width="20" height="20" alt="Поиск на сайте">
Относится ко всем картинкам, плюс надо точки в конце `alt` для всех картинок (у логотипа кстати есть)

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +              Хочу сюда!
Тут можно убрать скрытый текст, поскольку скринридер проговорит видимый текст и этого будет достаточно

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +              <img class="icon-favorite" src="images\icons\navigation-favorite.svg" width="18" height="17" alt="Избранное">
Тут будет двойное проговаривание, сначала скрытого текста, потом `alt` картинки.

Можно оставить только картинку, чтобы ее проговаривало, а скрытый текст делать в том случае, если например у нас картинка фоном лежит

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +      <img class="welcome-background" src="images\index-welcome-background.jpg" width="1200" height="485" alt="Панорама каньона и гор в Седоне.">
Эту предлагаю фоном положить

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +        <img class="welcome-background-divider" src="images\welcome-background-divider.svg" width="1200" height="57" alt="">
И эту тоже, сделаем через множественный фон

2022-10-27 07:16 UTC, pavel-niukalo commented on index.html
> +          </li>
Для более [простой стилизации](https://codesandbox.io/s/sedona-pymoy7) картинку давай вынесем за `div`:
```html
<li class="advantages-item">
  <div class="advantages-item-block-city">
    <h3 class="advantages-item-title">Настоящий городок</h3>
    <p class="advantages-item-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
  </div>
  
  <img class="advantages-photo photo-one" src="images\photo-1.jpg" width="800" height="384" alt="Старые магазинчики с деревьями перед фасадом и открытой верандой на втором этаже, на фоне знаменитых красных гор Седоны.">
</li>
```

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +          </li>
На 82 строке вместо `<div>` надо `<li>` указать

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +            <img class="advantages-icon-hotel" src="images\icons\icon-advantages-house.svg" width="76" height="72" type="icon">
Эти иконки предлагаю фоном потом сделать

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +        <a class="button button-search-hotel" href="#">ПОИСК ГОСТИНИЦЫ В Седоне</a>
Текст можно писать в обычном стиле (первая заглавная, дальше в нижнем регистре), а уже сделать их заглавными мы сможем через `css`

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +        <img class="subscribe-background" src="images\index-subscribe-background.jpg" width="1200" height="415" alt="Панорама каньона и гор в Седоне.">
Это тоже фоном сделаем

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +            <li class="footer-social-item">
Немного отступы поехали, у нас вложенные элементы должны быть отделены двумя пробелами, тут 4 получилось

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +              </a>
1. Иконку вставим через `<svg>`, поскольку она меняет цвет при наведении
2. У `img` нет атрибута `type`, но это решится, удалив `img` отсюда и заменив его на `svg`

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +              <a class="button" href="#">
Соц. сетям надо дать ссылки по тз

![image](https://user-images.githubusercontent.com/52506235/198214427-78736d36-7b56-4b80-a8de-ed74efe4bb4d.png)

2022-10-27 07:16 UTC, pavel-nyukalo commented on index.html
> +          </a>
Тут так же вставим через `svg`, поскольку меняется цвет 

![image](https://user-images.githubusercontent.com/52506235/198214593-e22096ba-7ee1-4e84-911a-e266e6bafdf9.png)

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
Если мы находимся на данной странице, то ссылку на эту же страницу можно убрать (оставить `href="#"`)

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
Здесь те же замечания, что и в `index`, так что не забудь тут поправить потом тоже

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +        <img class="filter-background" src="images\catalog-filter-background.png" width="1200" height="408" alt="Панорама каньона и гор в Седоне.">
Аналогично фоном

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +            <img class="breadcrumbs-icon-arrow" src="images\icons\breadcrumbs-arrow.svg" width="8" height="11" alt="Стрелка-разделитель">
Декоративные картинки можно будет фоном положить

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +        </a>
Тут аналогично, оставить один вариант, либо с картинкой и написать в `alt` "Показать ...", либо картинки фоном и оставляем скрытый текст

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +              </span>
Нет открывающего тега для этого спана

![image](https://user-images.githubusercontent.com/52506235/198216093-80df727c-e94a-4e75-a78a-ec63b0fa2065.png)

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +                <span class="product-card-rating-value">8,5</span></a>
Здесь цифру можно в спан не оборачивать, а стилизовать ссылку полностью

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +            </div>
Комментарии выше относятся ко всем карточкам

2022-10-27 07:16 UTC, pavel-nyukalo commented on catalog.html
> +    </footer>
Здесь все так же как в `index`

2022-10-27 07:46 UTC, AnnaKhVl commented on images/icons/rating-stars-2.svg
> +<svg width="140" height="37" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path d="m9 10 2.1 6.5H18l-5.6 4 2.2 6.5L9 23l-5.6 4 2.2-6.5-5.6-4h6.9L9 10Z" fill="#83B3D3"/></g><g
Поменяла во всех четырех карточках товара. 
Пока в комментах пометила, какое кол-во звёзд и что с ними делать потом:

<pre>
    <span class="product-card-rating-star four-stars visually-hidden">Четыре звезды</span>
        <img class="icon-star" src="images\icons\rating-star.svg" width="140" height="37" alt="">
<!-- 4 Звезды. (Потом фоном вставить и продублировать (background-repeat), или в разметку необходимое кол-во звезд) -->
    </span>
</pre>

2022-10-27 07:48 UTC, AnnaKhVl commented on images/icons/rating-stars-4.svg
> +<svg width="140" height="37" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path d="m9 10 2.1 6.5H18l-5.6 4 2.2 6.5L9 23l-5.6 4 2.2-6.5-5.6-4h6.9L9 10Z" fill="#83B3D3"/></g><g
Поменяла

2022-10-27 07:57 UTC, AnnaKhVl commented on images/icons/search-view-table.svg
> +<svg width="48" height="48" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)" fill="#000"><path d="M20 17h-4v6h4v-6ZM32 17h-4v6h4v-6ZM26 17h-4v6h4v-6ZM20 25h-4v6h4v-6ZM32 25h-4v6h
Заменила иконки на картинки без обводки

2022-10-27 08:02 UTC, AnnaKhVl commented on index.html
> +          <img class="page-header-logo" src="images\head-logo-sedona.svg" width="140" height="70" alt="Логотип «Город Седона».">
Заменила

_Блин, я забыла в валидаторе проверить всё(( ужас у меня там всё красное..._

2022-10-27 08:17 UTC, AnnaKhVl commented on index.html
> +              <img class="icon-search" src="images\icons\navigation-loop.svg" width="20" height="20" alt="Поиск на сайте">
Поправила

2022-10-27 08:18 UTC, AnnaKhVl commented on index.html
> +              Хочу сюда!
Ок

2022-10-27 08:22 UTC, AnnaKhVl commented on index.html
> +              <img class="icon-favorite" src="images\icons\navigation-favorite.svg" width="18" height="17" alt="Избранное">
Поняла, поправила везде

2022-10-27 08:33 UTC, AnnaKhVl commented on index.html
> +      <img class="welcome-background" src="images\index-welcome-background.jpg" width="1200" height="485" alt="Панорама каньона и гор в Седоне.">
Ок, когда буду прописывать CSS учту. 

Фоном только фоновую картинку или  лого "добро пожаловать" тоже?

2022-10-27 08:35 UTC, AnnaKhVl commented on index.html
> +        <img class="welcome-background-divider" src="images\welcome-background-divider.svg" width="1200" height="57" alt="">
Ок, сделаю комментарий в файле

2022-10-27 08:45 UTC, AnnaKhVl commented on index.html
> +          </li>
Сделала

2022-10-27 08:50 UTC, AnnaKhVl commented on index.html
> +          </li>
Исправила

2022-10-27 08:54 UTC, AnnaKhVl commented on index.html
> +            <img class="advantages-icon-hotel" src="images\icons\icon-advantages-house.svg" width="76" height="72" type="icon">
Ок, закомментила в файле

2022-10-27 08:56 UTC, AnnaKhVl commented on index.html
> +        <a class="button button-search-hotel" href="#">ПОИСК ГОСТИНИЦЫ В Седоне</a>
Ок, просто скопировала с макета, а там такая вакханалия. Исправила.

2022-10-27 08:58 UTC, AnnaKhVl commented on index.html
> +        <img class="subscribe-background" src="images\index-subscribe-background.jpg" width="1200" height="415" alt="Панорама каньона и гор в Седоне.">
Отметила

2022-10-27 09:00 UTC, AnnaKhVl commented on index.html
> +            <li class="footer-social-item">
Поправила

2022-10-27 09:58 UTC, AnnaKhVl commented on index.html
> +              </a>
Я или не дошла до тега `<svg>` или пропустила, в разделе графики его не было. 

Его вставлять ссылкой на файл аналогично изображению? 
`<svg class="footer-social-icon" src="images/icons/vk.svg" width="25" height="15" type="icon" alt="ВКонтакте."></svg>`

Или копировать длинный код из файла и его вставлять на страницу? 
`<svg width="25" height="15" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M24.12 1.8c.16-.54 0-.94-.8-.94H20.7c-.67 0-.98.34-1.15.73 0 0-1.33 3.2-3.22 5.27-.61.6-.9.8-1.23.8-.16 0-.41-.2-.41-.75v-5.1c0-.66-.19-.95-.74-.95H9.82c-.42 0-.67.3-.67.59 0 .62.95.76 1.04 2.51v3.8c0 .83-.15.98-.48.98-.9 0-3.06-3.2-4.34-6.88-.25-.72-.5-1-1.18-1H1.57c-.75 0-.9.34-.9.73 0 .68.89 4.07 4.14 8.55 2.17 3.06 5.23 4.72 8 4.72 1.68 0 1.88-.37 1.88-1v-2.32c0-.74.16-.88.7-.88.38 0 1.05.19 2.6 1.66 1.79 1.75 2.08 2.54 3.08 2.54h2.63c.75 0 1.12-.37.9-1.1-.23-.72-1.08-1.77-2.2-3.02-.62-.71-1.54-1.48-1.82-1.86-.39-.5-.28-.71 0-1.15 0 0 3.2-4.42 3.54-5.93Z" fill="#83B3D3"/></svg>`

Ещё я видела варианты, что в соцсетях прописываются ссылки, а `.svg` вставляется через `background-image` CSS.

От этого ещё зависит, что делать с  `<span class="visually-hidden">ВКонтакте</span>` - удалить и прописать у картинки `alt` "ВКонтакте." или оставить? Или название будет у ссылки если `svg` прописываем в CSS.

2022-10-27 10:15 UTC, AnnaKhVl commented on index.html
> +              <a class="button" href="#">
Прописала

2022-10-27 10:19 UTC, AnnaKhVl commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
Поменяла.
_Я как пользователь обычно наоборот тыкаю на эту ссылку, чтобы обновить её)_

2022-10-27 10:19 UTC, AnnaKhVl commented on catalog.html
> +            </a>
Поправила

2022-10-27 10:23 UTC, AnnaKhVl commented on catalog.html
> +        <img class="filter-background" src="images\catalog-filter-background.png" width="1200" height="408" alt="Панорама каньона и гор в Седоне.">
Прописала комментарий в файле. 
Картинку пока оставила, когда пропишу в CSS, то уберу её. Или сейчас убрать?

2022-10-27 10:25 UTC, AnnaKhVl commented on catalog.html
> +            <img class="breadcrumbs-icon-arrow" src="images\icons\breadcrumbs-arrow.svg" width="8" height="11" alt="Стрелка-разделитель">
Прописала комментарий в файле

2022-10-27 10:31 UTC, AnnaKhVl commented on catalog.html
> +        </a>
Оставлю тогда текст, а картинку фоном в CSS.

2022-10-27 10:32 UTC, AnnaKhVl commented on catalog.html
> +              </span>
Исправила

2022-10-27 10:40 UTC, AnnaKhVl commented on catalog.html
> +                <span class="product-card-rating-value">8,5</span></a>
Убрала `<span>`

2022-10-27 10:45 UTC, AnnaKhVl commented on catalog.html
> +            </div>
Исправила

2022-10-27 11:16 UTC, AnnaKhVl commented on index.html
> +          </a>
Исправила на `svg`

2022-10-27 11:33 UTC, AnnaKhVl commented on catalog.html
> +    </footer>
Исправлено

2022-11-15 12:05 UTC, pavel-nyukalo commented on index.html
> +      <img class="welcome-background" src="images\index-welcome-background.jpg" width="1200" height="485" alt="Панорама каньона и гор в Седоне.">
Добро пожаловать оставим в разметке, только горы фоном (и нижнюю полосочку)

2022-11-15 12:06 UTC, pavel-nyukalo commented on index.html
> +          </li>
Тоже надо, чтобы опять же проще стилизовать

2022-11-15 12:07 UTC, pavel-nyukalo commented on index.html
> +              </a>
Нам нужно менять цвет у иконки при наведении и лучший вариант - вставить через `svg`. Можно и фоновой картинкой конечно, но тогда при наведении придется менять ее, а это лишние запросы на сервер

2022-11-15 12:09 UTC, pavel-nyukalo commented on catalog.html
> +        <img class="filter-background" src="images\catalog-filter-background.png" width="1200" height="408" alt="Панорама каньона и гор в Седоне.">
Как удобнее, главное не забыть удалить

2022-11-15 12:10 UTC, pavel-nyukalo approved these changes

2022-11-15 12:10 UTC, merged